source 'http://rubygems.org'

group :default do
  gem 'gem_plugin', "0.2.3"
  gem 'highline', "1.6.1"
  gem 'hpricot', "0.8.6"
  gem 'jruby-openssl', "0.7.4"
  gem 'json_pure', "1.5.1"
  gem 'log4r'
  gem 'rails' , "3.0.7"
  gem 'rchardet', "1.3"
  gem 'ruby-debug', "0.10.4"
  gem 'ruby-debug-base', "0.10.4"
  gem 'rubyzip', "0.9.4"
  gem 'sources', "0.0.1"
  gem 'tzinfo', "0.3.27"
  gem 'unit_record', "0.9.1"
end


group :development do
  gem 'mongrel', "1.1.5"
  gem 'rspec', "2.6.0"
  gem 'rspec-core', "2.6.3"
  gem 'rspec-expectations', "2.6.0"
  gem 'rspec-mocks', "2.6.0"
  gem 'rspec-rails', "2.6.0"
end
